# .cargo/config.toml

[profile.difftests]
inherits = "dev"
rustflags = [
{% if coverage_area == "workspace-only" %}
{% elsif coverage_area == "all" %}
  "-C", "instrument-coverage",
{% endif %}
  "--cfg", "cargo_difftests",
]

{% if coverage_area == "workspace-only" %}
[build]
rustc-wrapper = "rustc-wrapper-difftests"
rustc-workspace-wrapper = "rustc-wrapper-difftests-workspace"
{% endif %}

[env]
RUST_TEST_THREADS = "1"

[unstable]
profile-rustflags = true
