on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  rerun-dirty-tests-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy, llvm-tools-preview
      
      - name: Install binutils
        run: cargo install cargo-binutils

      - name: Set old commit (push)
        if: ${{ github.event.before != null }}
        run: echo "OLD_COMMIT=${{ github.event.before }}" >> $GITHUB_ENV
      - name: Set old commit (pull_request)
        if: ${{ github.event.pull_request.base.sha != null }}
        run: echo "OLD_COMMIT=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV        

      - name: Print old commit
        run: echo $OLD_COMMIT

      - uses: dnbln/cargo-difftests-rerun-dirty-action@e02542cca4f6b17095ac53725987bca1acf82b4e
        with:
          commit-to-diff-with: ${{ env.OLD_COMMIT }}
          index-root: sample/cargo-difftests-sample-project/index_root
